apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
      matchLabels:
        app: nginx
  replicas: 1
  #restartPolicy: Always
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 
        imagePullPolicy: Never
        ports:
        - containerPort: 
          name : http
        - containerPort: 
          name : ssh
        - containerPort: 
          name : https
