apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
      matchLabels:
        app: nginx
  replicas: 1
  restartPolicy: Always
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name : http
        - containerPort: 22
          name : ssh
        - containerPort: 443
          name : https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
      matchLabels:
        app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name : mysql-pv
          mountPath : /var/lib/mysql
          subPath : mysql
      volumes :
      - name : mysql-pv
        persistentVolumeClaim :
          claimName : mysql-pvc
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
      matchLabels:
        app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wp-image
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 5050
          name: wordpress
      restartPolicy: Always
      initContainers:
      - name: init-db
        image: init-db-image
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
      matchLabels:
        app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: pma-image
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 5000
          name: phpmyadmin
      restartPolicy: Always
      initContainers:
      - name: init-db
        image: init-db-image
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql
---
