apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250 #custumize ip depending on ur cluster
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        app: nginx
spec:
    ports:
    - port : 
      targetPort: 
      name : http
    - port : 
      targetPort: 
      name : https
    - port : 
      targetPort: 
      name : ssh
    selector:
        app : nginx
    type: LoadBalancer
