apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    ports:
    - port : 5050
      targetPort: 5050
    externalIPs :
    - 192.168.99.103
    selector:
        app : wordpress
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin
    labels:
        app: phpmyadmin
spec:
    ports:
    - port : 5000
      targetPort: 5000
    externalIPs :
    - 192.168.99.103
    selector:
        app : phpmyadmin
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    ports:
    - port : 3306
    selector:
        app : mysql
    type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.101-192.168.99.107
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        app: nginx
spec:
    ports:
    - port : 80
      targetPort: 80
      name : http
    - port : 443
      targetPort: 443
      name : https
    - port : 22
      targetPort: 22
      name : ssh
    externalIPs :
    - 192.168.99.103
    selector:
        app : nginx
    type: LoadBalancer
---
